package utils.helpers

import java.lang.Long.parseLong
import java.util.*

/**
 * Simple utility method generating a numeric UUID string.
 *
 * @return string parsed from the Long representation of the hex UUID generated by the java.util.UUID tool.
 */
fun generateNumericUUID(): String {
    val uuid = UUID.randomUUID().toString().replace("-", "")
    var newUUID = ""
    for (i in 0..8) {
        newUUID += uuid.random()
    }
    return parseLong(newUUID, 16).toString()
}